### ISSUE TITLE
Missing dependabot-script MIT license

### ISSUE THREAD

**Issue by jurre** [paschdan/dependabot-enterprise-action#1]
Hi, first off, cool use of Dependabot 👍 

I noticed though that the files in https://github.com/paschdan/dependabot-enterprise-action/tree/1c1d530ba0b01fd51e7cdf177e953983386c1ce0/dependabot-script appear to come from https://github.com/dependabot/dependabot-script, but the MIT license has been stripped out.

Could you please put the license back for the code that was derived from that repository?

Thanks!

**Comment by paschdan** [comment]
Hi, sure can do this but the script is now almost a complete rewrite, stripped out not needed things, added other functionality ( e.g. edit existing PRs)
